/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Andy
 * Created: 16/05/2023
 */

-- tables for order management
CREATE TABLE ORDERS(
ORDERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
-- USERID will be foreign key to USER TABLE
USERID INTEGER NOT NULL,
ORDERDATE DATE NOT NULL,
-- ORDERPRICE DOUBLE NOT NULL,
SUBMIT BOOLEAN DEFAULT false,
ACTIVE BOOLEAN DEFAULT True,
PRIMARY KEY(ORDERID)
);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 1, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 1, '05/05/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 2, '03/07/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 2, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 100, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 3, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 3, '05/05/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 3, '03/07/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 3, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 4, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 4, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 4, '05/05/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 4, '03/07/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 5, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 200, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 1, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 1, '05/05/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 2, '03/07/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 2, '12/12/2023');
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE) VALUES ( 100, '12/12/2023');

CREATE TABLE CART(
CARTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
ORDERID INTEGER NOT NULL,
-- PRODUCTID will be foreign key to PRODUCT TABLE
PRODUCTID INTEGER NOT NULL,
ACTIVE BOOLEAN DEFAULT True,
FOREIGN KEY(ORDERID) REFERENCES ORDERS(ORDERID)
);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 501);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 502);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 2, 503);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 2, 504);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 505);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 501);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 502);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 2, 503);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 2, 504);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 505);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 501);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 502);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 2, 523);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 554);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 535);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 561);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 522);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 4, 543);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 4, 504);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 4, 505);