/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Andy
 * Created: 16/05/2023
 */

-- tables for order management
CREATE TABLE ORDERS(
ORDERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
USERID INTEGER NOT NULL,
ORDERDATE DATE NOT NULL,
ORDERPRICE DOUBLE NOT NULL,
PRIMARY KEY(ORDERID)
);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 100, '12/12/2023', 100.40);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 169, '12/12/2023', 320.20);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 110, '12/12/2023', 400.00);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 888, '12/12/2023', 50.80);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 100, '12/12/2023', 20.50);
