/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Andy
 * Created: 16/05/2023
 */

-- tables for order management
CREATE TABLE ORDERS(
ORDERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1), 
-- USERID will be foreign key to USER TABLE
USERID INTEGER NOT NULL,
ORDERDATE DATE NOT NULL,
ORDERPRICE DOUBLE NOT NULL,
PRIMARY KEY(ORDERID)
);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 100, '12/12/2023', 100.40);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 169, '05/05/2023', 320.20);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 110, '03/07/2023', 400.00);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 888, '12/12/2023', 50.80);
INSERT INTO ISDUSER.ORDERS (USERID, ORDERDATE, ORDERPRICE) VALUES ( 100, '12/12/2023', 20.50);


CREATE TABLE CART(
CARTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
ORDERID INTEGER NOT NULL,
-- PRODUCTID will be foreign key to PRODUCT TABLE
PRODUCTID INTEGER NOT NULL,
FOREIGN KEY(ORDERID) REFERENCES ORDERS(ORDERID)
);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 501);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 502);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 503);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 3, 504);
INSERT INTO ISDUSER.CART (ORDERID, PRODUCTID) VALUES ( 1, 505);